import { IMG } from "./catalogs";
import {
  DISCLAIMER,
  SECTION_LABEL,
  type Concept,
  type ConceptSection,
  type DealCheck,
  type SectionKey,
} from "./types";

function dc(karat: string, craft: string): DealCheck {
  return {
    weighOnScale: "وزن باید روی ترازوی فروشگاه خوانده شود، نه از روی عکس.",
    karat,
    craftFeeSeparate: craft,
    returnPolicy: "بازگشت فقط با جعبهٔ سالم و قطعهٔ بدون خط. جعبه بخشی از محصول است.",
    notAdvice: DISCLAIMER,
  };
}

function sec(key: SectionKey, body: string, imageUrl: string): ConceptSection {
  return { key, title: SECTION_LABEL[key], body, imageUrl };
}

export const SEED: Concept[] = [
  {
    id: "seed-shab-madar",
    title: "قاب کتاب‌نما × گردنی مادر",
    lede: "شب تولد مادر با جلد چرم، نه با جعبهٔ مخمل فروشگاهی. قطعه آخر باز می‌شود.",
    occasion: "birthday",
    productKind: "necklace",
    productName: "گردنی کارشده",
    audience: "مادر",
    heroImage: "/packages/book-necklace.jpg",
    shellName: "قاب کتاب‌نما",
    interiorName: "چاه مخمل به فرم قطعه",
    companionName: "دفترچهٔ داستان",
    ritualSeconds: 42,
    createdAt: "2026-09-01T09:00:00.000Z",
    seeded: true,
    source: "seed",
    note: "غافلگیری آرام برای مادر.",
    dealCheck: dc("عیار ۱۸ (۷۵۰) روی خود زنجیر.", "اجرت کار جدا از مظنه؛ دو خط روی فاکتور."),
    sections: [
      sec("product", "گردنی ۱۸ عیار با کار دست روی حلقهٔ اتصال. طول زنجیر در فاکتور می‌آید.", "/packages/book-necklace.jpg"),
      sec("packageExterior", "جلد چرم تیره شبیه نسخهٔ قدیمی. روی عطف فقط نوار موم باریک.", "/packages/book-necklace.jpg"),
      sec("packageInterior", "چاه مخمل دقیقاً به فرم گردنی. قطعه در صفحهٔ وسط کتاب خوابیده.", IMG.velvet),
      sec("unboxing", "حدود ۴۲ ثانیه: نوار ← موم ← ورق‌زدن صفحات خالی ← رسیدن به چاه قطعه.", IMG.ritual),
      sec("companion", "دفترچهٔ هشت‌صفحه با خاطرهٔ کوتاه از مادر. قیمت داخل دفترچه نیست.", "/packages/book-medallion.jpg"),
      sec("story", "کتاب را می‌دهد، نه جعبه را. مادر اول متن را می‌بیند، بعد فلز را.", "/packages/book-necklace.jpg"),
      sec("authenticity", "انگ ۱۸، وزن روی ترازو، فاکتور با اجرت جدا.", IMG.scale),
      sec("dealCheck", "وزن روی ترازو. عیار ۱۸. اجرت جدا از مظنه. بازگشت با جلد سالم. این توصیهٔ مالی نیست.", IMG.scale),
      sec("production", "هر جلد برای یک سفارش صحافی می‌شود. موجودی ویترین نیست.", IMG.velvet),
    ],
  },
  {
    id: "seed-jome-home",
    title: "جعبهٔ گردو × دستبند جمعه",
    lede: "مهمانی خانگی جمعه. کشوی گردو روی میز می‌ماند؛ دستبند بعد از چای دیده می‌شود.",
    occasion: "celebration",
    productKind: "bracelet",
    productName: "دستبند کارشده",
    audience: "میزبان یا مهمان جمعه",
    heroImage: "/packages/walnut-bracelet.jpg",
    shellName: "جعبهٔ گردو کشویی",
    interiorName: "سینی جیر",
    companionName: "گواهی موم‌خورده",
    ritualSeconds: 40,
    createdAt: "2026-09-02T09:00:00.000Z",
    seeded: true,
    source: "seed",
    note: "جعبه روی میز مهمانی بماند.",
    dealCheck: dc("عیار ۱۸ روی قفل.", "اجرت جدا از مظنه."),
    sections: [
      sec("product", "دستبند با قفل قابل‌تست. اندازه مچ قبل از ساخت بسته می‌شود.", "/packages/walnut-bracelet.jpg"),
      sec("packageExterior", "چوب گردو روغن‌خورده، کشوی برنجی، بدون لولای پیدا.", "/packages/walnut-bracelet.jpg"),
      sec("packageInterior", "سینی جیر داخل کشو. دستبند حلقه شده در چاه کم‌عمق.", "/packages/walnut-bracelet.jpg"),
      sec("unboxing", "۴۰ ثانیه: لمس چوب ← کشیدن کشو ← دیدن گواهی کناری ← برداشتن دستبند.", IMG.ritual),
      sec("companion", "گواهی موم‌خورده کنار سینی. وزن و عیار؛ بدون قیمت روز.", IMG.scale),
      sec("story", "جمعه است و خانه پر. جعبه شبیه ظرف پذیرایی است تا کیسهٔ جواهر.", "/packages/walnut-bracelet.jpg"),
      sec("authenticity", "انگ روی قفل، وزن، فاکتور جدا.", IMG.scale),
      sec("dealCheck", "وزن روی ترازو. عیار ۱۸. اجرت جدا. بازگشت با جعبهٔ بدون خط خوردگی چوب.", IMG.scale),
      sec("production", "هر کشو از یک تخته بریده می‌شود. رگه‌ها تکرار نمی‌شوند.", "/packages/walnut-bracelet.jpg"),
    ],
  },
  {
    id: "seed-host-plaque",
    title: "غلاف ابریشم × پلاک میزبان",
    lede: "ورود به خانهٔ کسی. غلاف ابریشم و چای کتان؛ پلاک آخر باز می‌شود.",
    occasion: "host",
    productKind: "plaque",
    productName: "پلاک حک‌شده",
    audience: "میزبان",
    heroImage: "/packages/silk-plaque.jpg",
    shellName: "غلاف ابریشم و موم",
    interiorName: "نشیمن نمد فشرده",
    companionName: "چای کتانی",
    ritualSeconds: 38,
    createdAt: "2026-09-03T09:00:00.000Z",
    seeded: true,
    source: "seed",
    note: "برای کسی که در خانه‌اش باز کرده.",
    dealCheck: dc("عیار ۱۸ پشت پلاک.", "اجرت حک جدا از مظنه."),
    sections: [
      sec("product", "پلاک با سطح آرام. نام اگر بیاید فقط یک واژه است.", "/packages/silk-plaque.jpg"),
      sec("packageExterior", "غلاف ابریشم زغالی، نخ و مهر موم سرخ.", "/packages/silk-plaque.jpg"),
      sec("packageInterior", "نمد فشرده داخل غلاف. پلاک تکان نمی‌خورد.", IMG.velvet),
      sec("unboxing", "۳۸ ثانیه: شکستن موم ← کشیدن نخ ← چای کتان ← پلاک.", IMG.ritual),
      sec("companion", "چای در کیسهٔ کتان. میزبان همان شب می‌تواند دم کند.", "/packages/silk-plaque.jpg"),
      sec("story", "هدیه به خانه‌ای که پذیرفته، نه به ویترینی که فروخته.", "/packages/silk-plaque.jpg"),
      sec("authenticity", "انگ پشت پلاک، وزن، فاکتور.", IMG.scale),
      sec("dealCheck", "وزن روی ترازو. عیار ۱۸. اجرت حک جدا. بازگشت با غلاف پاره نشده.", IMG.scale),
      sec("production", "هر غلاف دوخته می‌شود. موم همان روز زده می‌شود.", "/packages/silk-plaque.jpg"),
    ],
  },
  {
    id: "seed-ingot-nowruz",
    title: "قاب ایستاده × شمش اماراتی",
    lede: "شمش دیده می‌شود، اما هنوز در قاب خودش است. سریال از پنجره خوانده می‌شود.",
    occasion: "ingot",
    productKind: "ingot",
    productName: "شمش اماراتی",
    audience: "خریدار وزن‌محور",
    heroImage: "/packages/ingot-frame.jpg",
    shellName: "قاب ایستادهٔ شمش",
    interiorName: "کشوی گواهی",
    companionName: "گواهی موم‌خورده",
    ritualSeconds: 44,
    createdAt: "2026-09-04T09:00:00.000Z",
    seeded: true,
    source: "seed",
    note: "سریال باید از بیرون خوانده شود.",
    dealCheck: dc("۲۴ عیار (۹۹۹).", "حق ضرب و پک جدا از مظنه. اجرت کارشده روی شمش نیست."),
    sections: [
      sec("product", "شمش با سریال و هولوگرام پالایشگاه. وزن ضرب‌شده روی سطح.", "/packages/ingot-frame.jpg"),
      sec("packageExterior", "قاب عمودی لاک‌خورده با پنجرهٔ سریال.", "/packages/ingot-frame.jpg"),
      sec("packageInterior", "کشوی باریک فاکتور در پایه. شمش در قاب قفل است تا آیین تمام شود.", "/packages/ingot-frame.jpg"),
      sec("unboxing", "۴۴ ثانیه: خواندن سریال از پنجره ← کشوی فاکتور ← آزاد کردن قاب ← شمش.", IMG.ritual),
      sec("companion", "گواهی موم‌خورده در کشو. هولوگرام روی خود شمش است نه روی کاغذ.", IMG.scale),
      sec("story", "این هدیه وزن دارد و حرف کم. قاب می‌ایستد روی میز عید، مثل یک شیء نه یک بسته.", "/packages/ingot-frame.jpg"),
      sec("authenticity", "سریال، هولوگرام پالایشگاه، وزن ضرب، فاکتور در کشو.", IMG.scale),
      sec("dealCheck", "وزن روی ترازو تطبیق با ضرب. ۲۴ عیار. حق ضرب جدا از مظنه. بازگشت با قاب و هولوگرام سالم. توصیهٔ مالی نیست.", IMG.scale),
      sec("production", "قاب برای وزن مشخص ساخته می‌شود. شمش ۱۰ گرمی در قاب ۱۰ گرمی می‌نشیند.", "/packages/ingot-frame.jpg"),
    ],
  },
  {
    id: "seed-engagement",
    title: "لاک و صدف × ست نامزدی",
    lede: "ست در دو چاه مخمل. شمع تاریخ‌دار فقط برای همان شب.",
    occasion: "celebration",
    productKind: "set",
    productName: "ست هماهنگ",
    audience: "جفت",
    heroImage: "/packages/lacquer-set.jpg",
    shellName: "لاک مشکی و صدف",
    interiorName: "طبقهٔ دوگانه",
    companionName: "شمع تاریخ‌دار",
    ritualSeconds: 41,
    createdAt: "2026-09-05T09:00:00.000Z",
    seeded: true,
    source: "seed",
    note: "ست جدا فروخته نشود.",
    dealCheck: dc("۱۸ عیار هر دو قطعه.", "اجرت ست یک‌جا؛ مظنه جدا."),
    sections: [
      sec("product", "گردنی کوچک و گوشوارهٔ هماهنگ. ست یک زبان ساخت دارد.", "/packages/lacquer-set.jpg"),
      sec("packageExterior", "لاک مشکی، در صدفی. نور فقط روی رگهٔ صدف.", "/packages/lacquer-set.jpg"),
      sec("packageInterior", "دو چاه مخمل روی طبقهٔ بالا، گواهی پایین.", "/packages/lacquer-set.jpg"),
      sec("unboxing", "۴۱ ثانیه: در صدفی ← شمع ← طبقهٔ بالا ← ست.", IMG.ritual),
      sec("companion", "شمع با تاریخ مناسبت روی نوار کاغذی.", "/packages/lacquer-set.jpg"),
      sec("story", "شب نامزدی باید یک شیء مشترک داشته باشد نه دو جعبهٔ جدا.", "/packages/lacquer-set.jpg"),
      sec("authenticity", "انگ هر قطعه، وزن جدا، فاکتور واحد.", IMG.scale),
      sec("dealCheck", "وزن هر قطعه روی ترازو. عیار ۱۸. اجرت ست جدا از مظنه. بازگشت با در صدفی سالم.", IMG.scale),
      sec("production", "ست در یک پوسته می‌ماند مگر درخواست کتبی برای جدایی.", "/packages/lacquer-set.jpg"),
    ],
  },
  {
    id: "seed-friend-earrings",
    title: "استوانهٔ پلمپ × گوشوارهٔ دوست",
    lede: "بسته‌ای شبیه محمولهٔ بایگانی. کارت از شکاف، بعد جفت گوشواره.",
    occasion: "birthday",
    productKind: "earrings",
    productName: "گوشواره جفت",
    audience: "دوست",
    heroImage: "/packages/cylinder-earrings.jpg",
    shellName: "استوانهٔ پلمپ",
    interiorName: "چاه مخمل دایره",
    companionName: "کارت دست‌نویس",
    ritualSeconds: 36,
    createdAt: "2026-09-06T09:00:00.000Z",
    seeded: true,
    source: "seed",
    note: "سبک برای بردن به مهمانی.",
    dealCheck: dc("۱۸ عیار هر گوش.", "اجرت جفت جدا از مظنه."),
    sections: [
      sec("product", "جفت متقارن. وزن هر گوش روی برگه جدا نوشته می‌شود.", "/packages/cylinder-earrings.jpg"),
      sec("packageExterior", "لولهٔ مقوای فشرده با پلمپ موم. شکاف کارت.", "/packages/cylinder-earrings.jpg"),
      sec("packageInterior", "چاه مخمل دایره در ته استوانه.", IMG.velvet),
      sec("unboxing", "۳۶ ثانیه: پلمپ ← کارت از شکاف ← درپوش ← جفت.", IMG.ritual),
      sec("companion", "کارت دست‌نویس؛ یک جمله از خریدار.", IMG.companions),
      sec("story", "دوست باید بتواند بسته را زیر میز پنهان کند. استوانه این کار را می‌کند.", "/packages/cylinder-earrings.jpg"),
      sec("authenticity", "انگ، وزن جفت، فاکتور.", IMG.scale),
      sec("dealCheck", "وزن روی ترازو. عیار ۱۸. اجرت جدا. بازگشت با استوانهٔ پلمپ‌دار.", IMG.scale),
      sec("production", "قطر استوانه با اندازهٔ چاه گوشواره یکی است.", "/packages/cylinder-earrings.jpg"),
    ],
  },
  {
    id: "seed-rooftop",
    title: "پوست‌نباتی × دستبند پشت‌بام",
    lede: "پارتی پشت‌بام. کاغذ مچاله، عسل، بعد النگو. هیچ نوارچسبی نیست.",
    occasion: "celebration",
    productKind: "bracelet",
    productName: "دستبند کارشده",
    audience: "جمع شبانه",
    heroImage: "/packages/candy-bangle.jpg",
    shellName: "پوست‌نباتی",
    interiorName: "سینی جیر پیچیده در کاغذ",
    companionName: "عسل کوچک",
    ritualSeconds: 39,
    createdAt: "2026-09-07T09:00:00.000Z",
    seeded: true,
    source: "seed",
    note: "بدون روبان پلاستیکی.",
    dealCheck: dc("۱۸ عیار.", "اجرت جدا از مظنه."),
    sections: [
      sec("product", "النگوی بسته یا دستبند با قفل پنهان. برای شب باید راحت باشد.", "/packages/candy-bangle.jpg"),
      sec("packageExterior", "کاغذ بافت‌دار به شیوهٔ نبات. باز کردنش کار دست است.", "/packages/candy-bangle.jpg"),
      sec("packageInterior", "سینی جیر کوچک داخل کاغذ.", "/packages/candy-bangle.jpg"),
      sec("unboxing", "۳۹ ثانیه: تا کردن کاغذ ← عسل ← رسیدن به فلز.", IMG.ritual),
      sec("companion", "شیشهٔ کوچک عسل با نخ کتان.", "/packages/book-medallion.jpg"),
      sec("story", "پشت‌بام رسمی نیست. بسته هم نباید رسمیِ ویترین باشد.", "/packages/candy-bangle.jpg"),
      sec("authenticity", "انگ، وزن، فاکتور در پاکت تاشده داخل کاغذ.", IMG.scale),
      sec("dealCheck", "وزن روی ترازو. عیار ۱۸. اجرت جدا. بازگشت با کاغذ پاره نشده سخت است؛ قبل از باز کردن تصمیم بگیر.", IMG.scale),
      sec("production", "هر پوست یک‌بار تا می‌شود. دوباره بسته‌بندی همان شکل را نمی‌دهد.", "/packages/candy-bangle.jpg"),
    ],
  },
  {
    id: "seed-father",
    title: "آینه پشت در × گردنی پدر",
    lede: "جعبه باز می‌شود و زنجیر دو بار دیده می‌شود: در چاه و در آینه.",
    occasion: "birthday",
    productKind: "necklace",
    productName: "گردنی کارشده",
    audience: "پدر",
    heroImage: "/packages/mirror-chain.jpg",
    shellName: "قاب کتاب‌نما با آینه",
    interiorName: "آینه پشت در",
    companionName: "کشوی گواهی",
    ritualSeconds: 40,
    createdAt: "2026-09-08T09:00:00.000Z",
    seeded: true,
    source: "seed",
    note: "سنگین و کم‌حرف.",
    dealCheck: dc("۱۸ عیار.", "اجرت جدا از مظنه."),
    sections: [
      sec("product", "زنجیر مردانه با حلقهٔ اتصال محکم. طول در فاکتور.", "/packages/mirror-chain.jpg"),
      sec("packageExterior", "جلد سنگین، دستگیرهٔ فرو رفته.", "/packages/mirror-chain.jpg"),
      sec("packageInterior", "آینهٔ دودی پشت در. چاه مخمل در کف.", "/packages/mirror-chain.jpg"),
      sec("unboxing", "۴۰ ثانیه: در ← آینه ← کشوی گواهی ← زنجیر.", IMG.ritual),
      sec("companion", "گواهی در کشوی پایه. کارت صدا به صفحهٔ داستان همین پرونده.", IMG.companions),
      sec("story", "پدر باید وزن جعبه را در دست حس کند قبل از دیدن فلز.", "/packages/mirror-chain.jpg"),
      sec("authenticity", "انگ، وزن، فاکتور.", IMG.scale),
      sec("dealCheck", "وزن روی ترازو. عیار ۱۸. اجرت جدا. بازگشت با آینهٔ بدون خط.", IMG.scale),
      sec("production", "آینه برای این جلد بریده می‌شود. تعویض بعدی رنگ را عوض می‌کند.", "/packages/mirror-chain.jpg"),
    ],
  },
  {
    id: "seed-host-cylinder",
    title: "استوانه × پلاک ورود",
    lede: "برای میزبانی که نباید روی میز شلوغ جعبهٔ پهن بگذارد.",
    occasion: "host",
    productKind: "plaque",
    productName: "پلاک حک‌شده",
    audience: "میزبان",
    heroImage: "/packages/cylinder-plaque.jpg",
    shellName: "استوانهٔ پلمپ",
    interiorName: "نشیمن نمد",
    companionName: "گواهی از شکاف",
    ritualSeconds: 36,
    createdAt: "2026-09-09T09:00:00.000Z",
    seeded: true,
    source: "seed",
    note: "قائم روی میز بایستد.",
    dealCheck: dc("۱۸ عیار.", "اجرت حک جدا."),
    sections: [
      sec("product", "پلاک با زنجیر کوتاه. سطح برای یک نقش کوچک.", "/packages/cylinder-plaque.jpg"),
      sec("packageExterior", "استوانهٔ ایستاده با موم سرخ.", "/packages/cylinder-plaque.jpg"),
      sec("packageInterior", "نمد ته لوله. پلاک عمودی می‌نشیند.", IMG.velvet),
      sec("unboxing", "۳۶ ثانیه: موم ← گواهی شکاف ← درپوش ← پلاک.", IMG.ritual),
      sec("companion", "گواهی از شکاف کناری، قبل از دیدن فلز.", IMG.companions),
      sec("story", "ورود باید سبک باشد. استوانه در دست یک نفر جا می‌شود.", "/packages/cylinder-plaque.jpg"),
      sec("authenticity", "انگ پشت پلاک، وزن، فاکتور.", IMG.scale),
      sec("dealCheck", "وزن روی ترازو. عیار ۱۸. اجرت جدا. بازگشت با پلمپ اگر هنوز نشکسته.", IMG.scale),
      sec("production", "ارتفاع استوانه با طول زنجیر هماهنگ است.", "/packages/cylinder-plaque.jpg"),
    ],
  },
  {
    id: "seed-honey-medallion",
    title: "قاب کتاب × پلاک مدالیون",
    lede: "جشن با عسل و مدالیون در چاه دایره. دفترچه کنار شیشه.",
    occasion: "celebration",
    productKind: "plaque",
    productName: "پلاک مدالیون",
    audience: "جمع خانوادگی",
    heroImage: "/packages/book-medallion.jpg",
    shellName: "قاب کتاب‌نما",
    interiorName: "چاه دایره",
    companionName: "عسل کوچک",
    ritualSeconds: 40,
    createdAt: "2026-09-10T09:00:00.000Z",
    seeded: true,
    source: "seed",
    note: "شیرینی کنار فلز.",
    dealCheck: dc("۱۸ عیار.", "اجرت جدا از مظنه."),
    sections: [
      sec("product", "پلاک مدالیون با لبهٔ نرم. مناسب آویز یا نگهداری در جعبه.", "/packages/book-medallion.jpg"),
      sec("packageExterior", "کتاب با صفحات خام و شیشهٔ عسل کنار جلد.", "/packages/book-medallion.jpg"),
      sec("packageInterior", "چاه دایره در صفحهٔ میانی.", IMG.velvet),
      sec("unboxing", "۴۰ ثانیه: جلد ← عسل ← دفترچه ← مدالیون.", IMG.ritual),
      sec("companion", "عسل و دفترچهٔ داستان کوتاه جشن.", "/packages/book-medallion.jpg"),
      sec("story", "جشن باید طعم داشته باشد. فلز تنها کافی نیست.", "/packages/book-medallion.jpg"),
      sec("authenticity", "انگ، وزن، فاکتور.", IMG.scale),
      sec("dealCheck", "وزن روی ترازو. عیار ۱۸. اجرت جدا. بازگشت با جلد و شیشهٔ نخ‌دار.", IMG.scale),
      sec("production", "چاه دایره با قطر مدالیون یکی است. لقی ندارد.", "/packages/book-medallion.jpg"),
    ],
  },
];

export function getSeedById(id: string): Concept | undefined {
  return SEED.find((c) => c.id === id);
}
