/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiGoldRouteImport } from './routes/api/gold'
import { Route as ApiWaveRouteImport } from './routes/api/wave'
import { Route as ConceptIdRouteImport } from './routes/concept/$id'
import { Route as StoryIdRouteImport } from './routes/story/$id'
import { Route as ApiBriefIdRouteImport } from './routes/api/brief/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoldRoute = ApiGoldRouteImport.update({
  id: '/api/gold',
  path: '/api/gold',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaveRoute = ApiWaveRouteImport.update({
  id: '/api/wave',
  path: '/api/wave',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptIdRoute = ConceptIdRouteImport.update({
  id: '/concept/$id',
  path: '/concept/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdRoute = StoryIdRouteImport.update({
  id: '/story/$id',
  path: '/story/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBriefIdRoute = ApiBriefIdRouteImport.update({
  id: '/api/brief/$id',
  path: '/api/brief/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/pulse': typeof PulseRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/gold': typeof ApiGoldRoute
  '/api/wave': typeof ApiWaveRoute
  '/concept/$id': typeof ConceptIdRoute
  '/story/$id': typeof StoryIdRoute
  '/api/brief/$id': typeof ApiBriefIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/pulse': typeof PulseRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/gold': typeof ApiGoldRoute
  '/api/wave': typeof ApiWaveRoute
  '/concept/$id': typeof ConceptIdRoute
  '/story/$id': typeof StoryIdRoute
  '/api/brief/$id': typeof ApiBriefIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/pulse': typeof PulseRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/gold': typeof ApiGoldRoute
  '/api/wave': typeof ApiWaveRoute
  '/concept/$id': typeof ConceptIdRoute
  '/story/$id': typeof StoryIdRoute
  '/api/brief/$id': typeof ApiBriefIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/pulse'
    | '/api/generate'
    | '/api/gold'
    | '/api/wave'
    | '/concept/$id'
    | '/story/$id'
    | '/api/brief/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/pulse'
    | '/api/generate'
    | '/api/gold'
    | '/api/wave'
    | '/concept/$id'
    | '/story/$id'
    | '/api/brief/$id'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/pulse'
    | '/api/generate'
    | '/api/gold'
    | '/api/wave'
    | '/concept/$id'
    | '/story/$id'
    | '/api/brief/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  PulseRoute: typeof PulseRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiGoldRoute: typeof ApiGoldRoute
  ApiWaveRoute: typeof ApiWaveRoute
  ConceptIdRoute: typeof ConceptIdRoute
  StoryIdRoute: typeof StoryIdRoute
  ApiBriefIdRoute: typeof ApiBriefIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gold': {
      id: '/api/gold'
      path: '/api/gold'
      fullPath: '/api/gold'
      preLoaderRoute: typeof ApiGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wave': {
      id: '/api/wave'
      path: '/api/wave'
      fullPath: '/api/wave'
      preLoaderRoute: typeof ApiWaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/$id': {
      id: '/concept/$id'
      path: '/concept/$id'
      fullPath: '/concept/$id'
      preLoaderRoute: typeof ConceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id': {
      id: '/story/$id'
      path: '/story/$id'
      fullPath: '/story/$id'
      preLoaderRoute: typeof StoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brief/$id': {
      id: '/api/brief/$id'
      path: '/api/brief/$id'
      fullPath: '/api/brief/$id'
      preLoaderRoute: typeof ApiBriefIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  PulseRoute: PulseRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiGoldRoute: ApiGoldRoute,
  ApiWaveRoute: ApiWaveRoute,
  ConceptIdRoute: ConceptIdRoute,
  StoryIdRoute: StoryIdRoute,
  ApiBriefIdRoute: ApiBriefIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
